name:              bluepencil
version:           0.0.1

ghc-options: -Wall -fwarn-tabs

default-extensions:
  - OverloadedStrings
  - QuasiQuotes

dependencies:
  - aeson                         >= 0.6        && < 0.12
  - base                          >= 4          && < 5
  - containers                    >= 0.5        && < 0.6
  - http-types                    >= 0.9        && < 1
  - text                          >= 1.2        && < 1.3
  - vector                        >= 0.10       && < 0.12

library:
  source-dirs: src
  exposed-modules:
    - BluePencil

tests:
  bluepencil-tests:
    source-dirs: tests
    main: Main.hs
    dependencies:
      - bluepencil
      - hspec
      - raw-strings-qq
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
